version: "3.8"

services:
  web:
    build: .
    ports:
      - "5005:5000"
    depends_on:
      - db
    command: poetry run python run.py

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pybazaar
      MYSQL_USER: vinda
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
