# Generated by Django 5.1.7 on 2025-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userprofile_options_alter_userprofile_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
