# Generated by Django 5.1.7 on 2025-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
