# Generated by Django 5.1.7 on 2025-03-28 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
