# Generated by Django 5.1.7 on 2025-03-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilitystatus",
            name="status_name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
