# Generated by Django 5.1.7 on 2025-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_availabilitystatus_status_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_key",
            field=models.CharField(max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=30),
        ),
    ]
