# Generated by Django 5.1.7 on 2025-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_category_key_alter_category_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_key",
            new_name="category_slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="SKU",
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
